package com.test.simplecrud.exceptions;

public enum Errors {
    ENCRYPTION_ERROR,
    DECRYPTION_ERROR,
    WRONG_KEY,
    USER_NOT_FOUND,
    VEHICLE_NOT_FOUND,
    OWNERSHIP_VALIDATION_FAILED,
    VEHICLE_ALREADY_REGISTERED, USER_ALREADY_REGISTERED, CYPHER_ERROR,
    BAD_REQUEST
}
